### ISSUE TITLE
no main field in the package.json

### ISSUE THREAD

**Issue by ghost** [sproutcore/TransformJS#2]
There is no "main" field to start at and no "script" field to run the rake build step, so installation requires manual intervention.

**Comment by jtaby** [comment]
The Rake build step is only really helpful if you're hacking on TransformJS itself. In that case, you should be able to just run `rake` in your command line. 

What main and script fields are you referring to?

**Comment by jtaby** [comment]
Closing issue pending further information regarding issue.
