### ISSUE TITLE
RotateZ direction

### ISSUE THREAD

**Issue by yukulele** [sproutcore/TransformJS#22]
transformJS turn element in a wrong way with rotateZ (except with ie filter polyfill (!))

natural css transform rotateZ direction is **↻** (clockwise)
transformJS rotateZ is **↺** (anticlockwise)
transfomrJS with filter polyfill (ie 6-8) is **↻** (clockwise)

**Comment by sbaechler** [comment]
This is stupid because the rotation direction in IE and Chrome are opposite.

**Comment by yukulele** [comment]
Yes, but modern browser (firefox, chrome, ...) should folow css rotation
