### ISSUE TITLE
Transforms using non-standard length values in matrix function (breaks Opera)

### ISSUE THREAD

**Issue by miketaylr** [sproutcore/TransformJS#7]
Firefox implemented the matrix function against the spec, which requires a `<number>` rather than a `<length>`.  [1] For this reason TransformJS doesn't work in Opera (which implemented according to spec), or probably other browsers that have implemented the spec ( for example, tell the script that Chrome doesn't have 3D and it breaks on 2D).

Perhaps the approach in https://github.com/sproutcore/TransformJS/blob/master/lib/css_hooks.js#L40 could be switched so the `translationUnit` only gets added for Firefox? Thoughts?

[1]  http://lists.w3.org/Archives/Public/www-style/2009Oct/0360.html

**Comment by jtaby** [comment]
I just pushed up a fix. Thanks for reporting the issue!
